### PR TITLE
Fix action reported on install error

### PR DESCRIPTION
**Pull request by forslund**
The install failure reported a remove failure instead of an install failure.

### CODE REVIEW

**Comment by krisgesling** [comment]
For me, doing a voice install of "openhab", it still speaks the successfully installed dialog even though a CloneException error gets raised by MSM. Are you seeing the same behaviour?

**Comment by forslund** [comment]
Not when using the latest (unreleased) msm. Using the current 0.8.4 release doesn't detect install errors.

**Comment by forslund** [comment]
Might want to add a better error message though it says there's a filesystem error when there's a git error...

**Comment by krisgesling** [comment]
Yep that was silly of me. 

Perhaps:
> "An error occurred while {action} {skill}. I was unable to clone the Skill from Github."

?

**Comment by forslund** [comment]
Good suggestion, will add that

**Comment by forslund** [comment]
PR Updated

**Comment by forslund** [comment]
Thanks, will you rebase and squash those last two commits before merging?

**Pull request merged**
